src/emqttc.erl
Hi!
I have made a little fix to remove this compile error:
>src/emqttc.erl:58: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
>ERROR: compile failed while processing /Users/assoulter/development/workspace/emqttc: rebar_abort
=> OTP 18.0 compatible

src/emqttc.app.src
Exrm is a release manager for elixir that uses `relx` internally. It automatically includes everything in `applications` and `included_applications` in the release. Adding the dependencies of `emqttc` into its `included_applications` enables elixir projects using `emqttc` to generate a release with zero configuration, using `exrm`.
=> Add included_applications to .app.src

.travis.yml, src/emqttc_protocol.erl
- use 18.x new Time API to replace erlang:now() (ballback to 17.x Time API if not exist)
- add OTP 18.x support in travis CI
=> Use new erlang Time API and include OTP 18.x in travis build

rebar.config
HTTPS should be the preferred method to connect to github to avoid problems with firewalls, and also to prevent man-in-middle attacks.
=> Use https for github dependencies

rebar.config, src/emqttc.app.src
It isn't used anywhere in emqttc.
=> Remove getopt dependency

src/emqttc.erl
This is a "fix" for #46 
When dealing with larger packets the `emqttc_packet:dump(Packet)` seems to slow down massively the `fsm client`.
=> Comment out log line

include/emqttc_packet.hrl, src/emqttc.erl
EMQTT will return the special QoS code 128 in case the subscriber has no authorization for the topic, but this case is not reflected in the current `sync_subscribe` specs.
This commit updates the sync_subscribe spec to take this into account.
=> Fix sync_subscribe spec

src/emqtt.erl
There is an error reported by logger when connecting to the server fails. This is I believe also what #84 mentions. Changing the stop reason to normal instead of the socket connection error avoids this.
=> Fix shutdown reason in case of connect error

.github/workflows/build_packages.yaml, .github/workflows/release.yaml, src/emqtt.erl
Add start link option `low_mem` mode, this PR is for emqtt_bench to have as many clients as possible but keep memory usage low.
That is achieved by
1.  forcing major GC 
1.  hibernate client proc after a 50ms receive timeout.
default: disabled
=> Add start link option low_mem 

.github/workflows/run_test_case.yaml, rebar.config, src/emqtt.erl, src/emqtt_quic.erl, test/emqtt_SUITE.erl, test/emqtt_test_lib.erl
- fix test
- add new option reconnect for TCP , TCP/SSL and QUIC 
This is a feature for emqtt bench for robustness test.
=> support automatic reconnect , tcp/ssl and quic

rebar.config
https://github.com/emqx/gun/compare/1.3.4...emqx:gun:1.3.7
fix: erlang:get_stacktrace() undef on OTP24
=> chore: fix undef function(bump gun to 1.3.7)

Makefile, changlog.md, src/emqtt.erl, test/emqtt_SUITE.erl
Prior to this fix, the expired retry timer may not get the chance
to refresh if it's not at the 'connected' state.
A ensure_retry_timer call is added to the state transition
from waiting_for_connack to connected
=> fix(emqtt): should retry after reconnect

changlog.md, src/emqtt.erl, test/emqtt_SUITE.erl
Prior to this commit, when the client created a TCP connection with the
server and the server did not respond with a `CONNACK` (for example
because the server is blocked due to overload), the client was stuck in
state `waiting_for_connack` without respecting the configured
`connect_timeout`.
=> Respect connect_timeout

src/emqtt.erl, test/emqtt_SUITE.erl
Do not resend packets that got published within the last `retry_interval`.
Before this commit, it can happen that a packet is resent even if the `retry_interval` is 30 seconds and a packet gets acked by the server within a few milliseconds.
Also, `retry_interval` unit was used wrongly at some places. Correct usage seems to be:
* The library user defines `retry_interval` in seconds.
* Within the library, `retry_interval` is milliseconds.
Also, I removed `non_parallel_tests` since it does not have any meaning in the group properties.
=> Resend only old packets

.github/workflows/build_packages.yaml
We dont need to upload artifacts while testing the PRs.
=> ci: upload artifacts only when release

rebar.config, rebar.config.script, src/emqtt.erl, test/emqtt_SUITE.erl
- Bump quicer to 0.0.111 for ubuntu22.04 LTS prebuild binaries.
- test with EMQX master branch since https://github.com/emqx/emqx/pull/9949 is merged
- disable force check on reconnect clean session option check since we need it for testing.
=> quicer 0.0.111

src/emqtt.erl, src/emqtt_ws.erl, test/emqtt_SUITE.erl, test/emqtt_connect_SUITE.erl, test/emqtt_frame_SUITE.erl, test/emqtt_props_SUITE.erl, test/emqtt_quic_SUITE.erl, test/emqtt_sock_SUITE.erl, test/emqtt_test_lib.erl
Also
* fixes a bug that `ws_connect` does not actually handle `inet:ip_address()` hosts.
* fixes and clarifies ipv6 connection process (also was broken for ws).
=> feat(connect): accept binary hosts

src/emqtt.erl, src/emqtt_internal.hrl, src/emqtt_sock.erl, test/emqtt_SUITE.erl, test/emqtt_test_lib.erl
`emqx_sock` defined an internal record for storing both the tcp and ssl socket ports.  However, when we have a TLS error such as `bad_certificate`, `ssl` sends a message containing the inner SSL socket, not this internal emqtt record, and there were missing clauses to handle that.
This caused `emqtt` to:
i) Hang indefinitely if `connect_timeout` is not specified; ii) Fail with `{error, connack_timeout}` if `connect_timeout` is a finite value.
=> fix(ssl): correctly handle ssl error events

src/emqtt.appup.src
emqtt_cli is not in use as library but EMQX appup check wants it otherwise:
```
ERROR: Appup file for 'emqtt' is not complete.
ERROR: Missing:#{down =>
[{"1.2.3.1",[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]},
{"1.2.3",[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]},
{<<"1.2.[0-2]">>,[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]}],
up =>
[{"1.2.3.1",[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]},
{"1.2.3",[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]},
{<<"1.2.[0-2]">>,
[{load_module,emqtt_cli,brutal_purge,soft_purge,[]}]}]}
ERROR: Incomplete appups found. Please inspect the output for more details.
```
=> upgrade(appup): add emqtt_cli to please emqx appup check

src/emqtt.erl
Sending messages using MQTT 5.0 failed when handling PUBREC, with the following error log:
```
State: connected, Unexpected Event: (cast, {mqtt_packet,{mqtt_packet_header,5,false,0,false},{mqtt_packet_puback,3,16,#{}},undefined})
```
=> fix: discard reason_code of PUBREC and PUBREL

rebar.config, src/emqtt.erl, src/emqtt_sock.erl, test/emqtt_SUITE.erl, test/emqtt_test_lib.erl
There is no need to call `ssl:controlling_process` to `self()` after ssl upgrade.
The socket is owned by `self()` already.
Also refined the return value for `connect` call in case `shutdown` happens while waiting for CONNACK.
=> fix(emqtt_sock): fix a race condition during ssl upgrade

src/emqtt_ws.erl
In order for wss to work, the contents of ws_transport_options needs to be at the same level as other ConnOpts.
This is required because gun requires two overrides for any non-standard TLS port:
```
{ ws_transport_options, [
{transport, tls},
{protocols,[http]}
]}
```
The first option is required to specify tls (obviously) since gun will only enable tls on port 443 due to this code in gun.erl:
```
default_transport(443) -> tls;
default_transport(_) -> tcp.
```
Any non-443 SSL connection would then require the "{transport, tls}" option added to ws_transport_options.
The second option is required because gun defaults to http2, which then fails.   Reducing the protocols to just http allows tls to succeed and thus wss will succeed.
One or both of these may become unnecessary in future …
=> ws_transport_options inserted at wrong level - WSS fails on non-443 TLS ports

README.md, rebar.config
This commit aims to fix the compilation errors related to cowlib and emqx_utils dependencies. Specifically, the changes include:
- Upgraded the cowlib dependency from version 2.11.0 to 2.12.1 to align with the requirement specified in cowboy's rebar.config.
- Added the path for emqx_utils in the rebar.config file, resolving the build problem where emqx_utils was not being fetched.
- Included build and test case badges in README.md to enhance project information.
=> Update cowlib dependency and add emqx_utils to rebar

.dockerignore, .github/workflows/build_packages.yaml, .github/workflows/run_static_checks.yaml, .github/workflows/run_test_case.yaml, Dockerfile.test, Makefile, include/emqtt.hrl, src/emqtt.erl, src/emqtt_frame.erl, src/emqtt_sock.erl, src/emqtt_ws.erl, test/emqtt_SUITE.erl, test/emqtt_connect_SUITE.erl, test/emqtt_quic_SUITE.erl, test/emqtt_test_lib.erl
There is a race condition (the cause of which is yet to be identified):
When TLS alert such as server-raise alert "certificate revoked", there is a chance for the client side ssl:connect call to return ok.
But right after this, if it tries to call setopts, {error, einval} is returned, then if it tries to send data {error, closed} is returned.
This makes the initial CONNECT packet send error to cause a crash from time to time.
This PR is to turn the {error, Reason} return into a shutdown reason, so it will not cause a gen_statem crash.
Also added a debug level log in case the send call returned error.
=> 1012 add debug log for connect errors and fix dialyzer

.github/workflows/run_test_case.yaml, src/emqtt_sock.erl
Similar to #196, but maintains compatibility with OTP25. ~Based on the implementation that RabbitMQ used in https://github.com/rabbitmq/rabbitmq-server/pull/7927~
=> feat: support OTP 26

src/emqtt.erl, src/emqtt_secret.erl, test/emqtt_SUITE.erl
By convention, any 0-arity function is considered a wrapped secret.
Part of EMQX-10808.
=> feat(opt): allow external wrapped secrets as passwords

include/emqtt.hrl, src/emqtt.erl, test/emqtt_SUITE.erl
This PR allows user to add `{auto_ack, never}` when they want to carry out QoS 2 protocol flow per each incoming publish manually.
Part of [EMQX-11049](https://emqx.atlassian.net/browse/EMQX-11049).
=> feat(autoack): add never option disabling automatic QoS2 flow

rebar.config, src/emqtt.erl, test/emqtt_custom_auth_SUITE.erl, test/emqtt_test_lib.erl
Part of https://emqx.atlassian.net/browse/EMQX-12658
To avoid pulling A LOT of EMQX dependencies just to test this, the new test suite instead expects a suitably configured EMQX to be running instead of managing it itself.  CI changes haven't been made at this moment to do such things, but the suite was run manually.
=> feat: allow handling custom authentication flows

src/emqtt.erl
We need logic stream. The QUIC stream id is not transparent to the user that user is not free to choice the stream id while create the stream, thus we need logical stream to present the 'session stream' persistency.
If the QUIC stream is closed or aborted, the logical stream could be kept alive by starting new stream where both endpoints exchange the logic stream id in the stream header. This is not done yet but written in mqtt-next spec.
=> feat(quic): support logical stream id

.github/workflows/run_test_case.yaml, README.md, rebar.config, rebar.config.script, src/emqtt.app.src, src/emqtt.erl, src/emqtt_cli.erl, src/emqtt_frame.erl, src/emqtt_quic.erl, src/emqtt_quic_connection.erl, src/emqtt_quic_stream.erl, src/emqtt_sock.erl
fixes #255 
Still a few dialyzer warnings are left, all related to `quic` calls.
=> fix: fix type specs and dialyzer checks

changelog.md, include/logger.hrl, src/emqtt.erl, test/emqtt_test_lib.erl
- prior to this fix, only `tcp_closed` and `ssl_closed` were handled at `waiting_for_connack` state.
- this PR adds the same handling for `tcp_error` and `ssl_error`.
- fixed map literal mutate compile warnings on otp 27
=> 241112 reconnect if socket error at wating_for_connack state

changelog.md, src/emqtt.erl, src/emqtt_quic_stream.erl, test/emqtt_SUITE.erl
see also changelog
- if socket error is returend when sending CONNECT, do not stop
but wait for the socket error event to trigger a retry
- update call ID so the `connect` caller can get a reply later
if `CONNACK` is received from a new socket
- ignore socket error and close event when at back-off/cool-down
state (reconnect) because we know it's a stale message.
=> 241112 reconnect if sending CONNECT returned transport error

README.md, changelog.md, src/emqtt.erl, src/emqtt_quic_connection.erl, src/emqtt_quic_stream.erl, src/emqtt_ws.erl, test/emqtt_SUITE.erl
- avoid OTP crash report by wrapping exit reason in `{shutdown,Reason}`
- reformat some code for readability
=> Improve logs and readability

.github/workflows/build_packages.yaml, .github/workflows/run_test_case.yaml, rebar.config.script, src/emqtt_quic_stream.erl
After peer abort recv, emqtt should abort send direction,
instead of aborting both dir.
also bump 0.2.4 which is unrelated to this fix.
=> fix(quic): correct handle peer recv abort

src/emqtt_sock.erl, src/emqtt_ws.erl
`gun` connection process can die after `gun:await_up`, in which case `upgrade` will hang
for a potentially long time.
=> fix(ws): avoiding hanging if gun connection process dies before upgrade

README.md
v.1.2.0 seems to be out of date, it didn't compile with my setup and then I noticed that v1.2.0 was four years old!
Only once I switched to 1.14.4 did everything work.
=> Please update README with latest version for rebar3 config

.github/workflows/run_test_case.yaml, rebar.config, src/emqtt.erl, test/emqtt_test_lib.erl
Similar to https://github.com/emqx/emqtt/pull/279
This time, the error is a bit different, but the effect is the same:
```
18:17:09.437 [info] [reason: {:tls_alert, {:certificate_revoked, ~c"TLS client: In state connection received SERVER ALERT: Fatal - Certificate Revoked\n"}}, msg: ~c"failed_to_send_connect_packet", clientid: "emqtt-erlang-9e2056f5415da439bfce"]
```
```
Testing apps.emqx.emqx_crl_cache_SUITE: *** FAILED test case 1 ***
%%% emqx_crl_cache_SUITE ==> t_revoked: FAILED
%%% emqx_crl_cache_SUITE ==> {{case_clause,{error,connack_timeout}},
[{emqx_crl_cache_SUITE,t_revoked,1,
[{file,"test/emqx_crl_cache_SUITE.erl"},{line,969}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
{test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]}, …
```
=> fix: hanging process when TLS alert happens during mqtt_connect (`tls_alert`)

rebar.config, src/emqtt.erl
Fixes [EMQX-14540](https://emqx.atlassian.net/browse/EMQX-14540)
Seems that `emqtt` treats keepalive as means to report its own liveness to the broker, but not to check the broker presence.
When `emqtt` sends `PINGREQ` on keepalive timer, it doesn't check that a `PINGRESP` comes. 
So if a TCP connection gets stalled (no packets find their routes), `emqtt` does not react to this.
However MQTT spec advises to close connection if `PINGRESP` is absent (3.1.2.10 Keep Alive):
> If a Client does not receive a PINGRESP packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.
So we introduce a timer to detect `PINGRESP` absence and close the connection. We do not schedule this timer on manual `ping` call assuming that the caller …
=> feat: respect pingresp timeout

src/emqtt.erl, test/emqtt_SUITE.erl, test/emqtt_test_lib.erl
https://github.com/emqx/emqtt/pull/190
https://github.com/emqx/emqtt/pull/279
https://github.com/emqx/emqtt/pull/286
=> port fixes to main-1.13
